// 예약자 더미 데이터 (실제 API 응답 구조에 맞춤)
// API 응답: { bottleId, bottleName, quantity, confirmedQuantity, status, noticeId, pickupUserBusinessId, createdAt, updatedAt }
export const extendedApplicants = [
  {
    id: 1,
    userId: 1,
    bottleId: 1,
    bottleName: "Glenfiddich 1993 Whisky Navi Single Cask",
    noticeId: 1,
    quantity: 2,
    confirmedQuantity: 2,
    status: "CONFIRMED",
    pickupUserBusinessId: 1,
    createdAt: "2026-01-10T14:23:00.000Z",
    updatedAt: "2026-01-11T10:00:00.000Z",
    // 추가 정보 (조인된 데이터)
    name: "홍길동",
    email: "whisky.lover@example.com",
    phone: "010-1234-5678",
    memberType: "일반",
    whiskeyNaviMembership: "VIP",
    whiskeyTalesMembership: "GOLD",
    pickupLocation: "강남점",
  },
  {
    id: 2,
    userId: 2,
    bottleId: 1,
    bottleName: "Glenfiddich 1993 Whisky Navi Single Cask",
    noticeId: 1,
    quantity: 5,
    confirmedQuantity: 3,
    status: "CONFIRMED",
    pickupUserBusinessId: 2,
    createdAt: "2026-01-10T15:45:00.000Z",
    updatedAt: "2026-01-11T10:00:00.000Z",
    name: "김영희",
    email: "scotch.master.premium@example.com",
    phone: "010-2345-6789",
    memberType: "업장",
    whiskeyNaviMembership: "GOLD",
    whiskeyTalesMembership: null,
    pickupLocation: "홍대점",
  },
  {
    id: 3,
    userId: 3,
    bottleId: 1,
    bottleName: "Glenfiddich 1993 Whisky Navi Single Cask",
    noticeId: 1,
    quantity: 3,
    confirmedQuantity: 3,
    status: "CONFIRMED",
    pickupUserBusinessId: 3,
    createdAt: "2026-01-11T09:12:00.000Z",
    updatedAt: "2026-01-11T10:00:00.000Z",
    name: "이철수",
    email: "whisky.fan.collection@example.com",
    phone: "010-3456-7890",
    memberType: "일반",
    whiskeyNaviMembership: "SILVER",
    whiskeyTalesMembership: "SILVER",
    pickupLocation: "부산점",
  },
];
